"""Compatibility facade for allowlist-based Obsidian Markdown import."""

from __future__ import annotations

from agent_hub.importing.allowlist import (
    ensure_path_allowed,
    is_relative_to,
    iter_markdown_files,
    load_allowlist,
    relative_import_path,
)
from agent_hub.importing.constants import (
    ALLOWED_TYPES,
    FIELD_OWNERS,
    REQUIRED_FIELDS,
    SENSITIVE_PATTERN,
    STATUS_VALUES,
    TYPE_COLUMNS,
    TYPE_DEFAULT_FIELDS,
    TYPE_DEFAULT_VALUES,
    TYPE_TABLES,
)
from agent_hub.importing.identity import (
    build_field_diffs,
    canonical_json,
    changed_fields_from_last,
    derive_import_key,
    hash_payload,
    import_metadata,
    item_values,
    json_default,
    normalize_value,
    row_values,
    user_metadata,
    values_equal,
)
from agent_hub.importing.markdown import (
    contains_secret,
    normalize_import_item,
    parse_markdown,
)
from agent_hub.importing.models import (
    ImportAllowlist,
    ImportItem,
    ImportResult,
    SyncResult,
)
from agent_hub.importing.store import (
    apply_import_item,
    ensure_import_agent,
    fetch_existing_import,
    fetch_project,
    insert_import_item,
    log_import_action,
    plan_import_item,
    update_import_item,
)
from agent_hub.importing.workflow import (
    import_markdown,
    load_import_items,
    log_sync_event,
    sync_markdown,
)

__all__ = [
    "ALLOWED_TYPES",
    "FIELD_OWNERS",
    "ImportAllowlist",
    "ImportItem",
    "ImportResult",
    "REQUIRED_FIELDS",
    "SENSITIVE_PATTERN",
    "STATUS_VALUES",
    "SyncResult",
    "TYPE_COLUMNS",
    "TYPE_DEFAULT_FIELDS",
    "TYPE_DEFAULT_VALUES",
    "TYPE_TABLES",
    "apply_import_item",
    "build_field_diffs",
    "canonical_json",
    "changed_fields_from_last",
    "contains_secret",
    "derive_import_key",
    "ensure_import_agent",
    "ensure_path_allowed",
    "fetch_existing_import",
    "fetch_project",
    "hash_payload",
    "import_markdown",
    "import_metadata",
    "insert_import_item",
    "is_relative_to",
    "item_values",
    "iter_markdown_files",
    "json_default",
    "load_allowlist",
    "load_import_items",
    "log_import_action",
    "log_sync_event",
    "normalize_import_item",
    "normalize_value",
    "parse_markdown",
    "plan_import_item",
    "relative_import_path",
    "row_values",
    "sync_markdown",
    "update_import_item",
    "user_metadata",
    "values_equal",
]
